name: Pulse Smoke Tests

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run smoke tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        PULSE_API_BASE_URL: ${{ secrets.PULSE_API_BASE_URL }}
        TEST_AREA: ${{ vars.TEST_AREA || 'tampa-bay' }}
        TEST_REGION: ${{ vars.TEST_REGION || 'FL' }}
        TEST_COUNTRY: ${{ vars.TEST_COUNTRY || 'US' }}
        TEST_TIMELINE: ${{ vars.TEST_TIMELINE || 'today' }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        ENABLE_SLACK_NOTIFICATIONS: ${{ vars.ENABLE_SLACK_NOTIFICATIONS || 'true' }}
        ENABLE_DISCORD_NOTIFICATIONS: ${{ vars.ENABLE_DISCORD_NOTIFICATIONS || 'false' }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL || 'info' }}
      run: npm run smoke

    - name: Run Jest tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        PULSE_API_BASE_URL: ${{ secrets.PULSE_API_BASE_URL }}
        SUPPRESS_LOGS: 'true'
      run: npm test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          test-results/

  auto-healing:
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: failure() && github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run auto-healing script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ENABLE_AUTO_HEALING: 'true'
      run: |
        echo "Auto-healing would run here"
        # npm run auto-heal

    - name: Create issue for failures
      if: failure()
      uses: actions/create-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: 'Smoke Tests Failed - ${{ github.run_id }}'
        body: |
          ## Smoke Tests Failed
          
          **Run ID:** ${{ github.run_id }}
          **Time:** ${{ github.event.head_commit.timestamp }}
          
          The automated smoke tests have failed. Please investigate the failures.
          
          [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        labels: 'bug,automated-test-failure'